### PR TITLE
feat: API event handler to proxy `event` through Nitro server

### LINKED ISSUE #34: Proxy through Nitro server
I would like everything to be proxied as [described in the docs](https://plausible.io/docs/proxy/introduction):

```
https://<yourdomain.com>/js/script.js -> https://plausible.io/js/script.js
https://<yourdomain.com>/api/event    -> https://plausible.io/api/event
```

In Nuxt normally this can be done easily by use of Nitro route rules, I imagine the following would work:

nuxt.config.ts:
```
routeRules: {
    '/api/event': {
      redirect: 'https://plausible.io/api/event',
    },
},
plausible: {
    apiHost: '/', <-- This doesnt work
},
```

The problem is that I cant set the `data-api` property as it is required and describe in the docs:

```
<script defer data-api="/api/event" data-domain="website.com" src="/js/script.js"></script>
```

If I set `apiHost` to `/` it makes the call go to `https:///api/event` instead of `/api/event`. If this would be fixed I guess it would work as shown above.

### PR DESCRIPTION
**Pull request by asonnleitner**
### 🔗 Linked issue

Resolves #34

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR implements proxy functionality for Plausible analytics events, allowing events to be proxied through the Nitro server instead of being sent directly to Plausible's servers. While the original issue suggested using Nitro route rules, this implementation uses a custom server handler for more control over the proxying process and better error handling.

Rather than relying on the Plausible script and its `data-api` attribute, this solution works with the `@barbapapazes/plausible-tracker` package that's bundled with the module. When proxy is enabled, the tracker automatically routes requests through the current origin.

Key changes:
- Added new configuration options:
  - `proxy`: Toggle to enable/disable proxy functionality (default: false)
  - `proxyBaseURL`: Customizable base URL for the proxy endpoint (default: '/api/event')
- Implemented server-side event handler that forwards requests to Plausible while preserving important headers
- Updated client-side plugin to automatically use the correct endpoint based on proxy configuration
- Added validation to prevent route conflicts
- Enhanced error handling with appropriate status codes and messages
- Updated documentation with new configuration options

Example usage:
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  plausible: {
    proxy: true, // Enable proxying through Nitro server
    proxyBaseURL: '/api/event', // Optional: customize the proxy endpoint
  }
})
```

### CODE REVIEW

**Comment by MickL** [comment]
Looks amazing! Unfortunately if I set 'proxyBaseURL' to '/event' it still goes to '/api/event'. Could you make this fix?

I have all my api routes '/api/**' proxied to my external api already so it cant be prefixed with api for me.

**Comment by johannschopplich** [comment]
@MickL `/api` is the default path of Nitro's internal API. Many modules rely on it, so proxying every sub-route may not be the best solution. If you want to change the default base URL, then please use the [`apiBaseURL`](https://nitro.build/config#apibaseurl) option of the Nitro config and change the event base URL of this module afterwards.

**Comment by MickL** [comment]
I have a very huge projects using tons of modules. Everything is fine for now. This seems to be a bug to me because even tho I changed proxyBaseURL, requests still go to '/api/event'

**Comment by MickL** [comment]
@asonnleitner I just realized that the whole PR is not working. Requests go to `/api/event` instead of `/api/__plausible_event__` which results in 404 - #34

**Pull request merged**
